// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DashboardApi from "./DashboardApi.bs.js";
import * as Stdlib_Promise from "@rescript/runtime/lib/es6/Stdlib_Promise.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function readErrorMessage() {
  return "Impossible de contacter dashboard-api.";
}

function pendingMatches(pendingRoomId, roomId) {
  if (pendingRoomId !== undefined) {
    return Primitive_object.equal(Primitive_option.valFromOption(pendingRoomId), roomId);
  } else {
    return false;
  }
}

function App(props) {
  let apiBaseUrl = DashboardApi.getApiBaseUrl();
  let match = React.useState(() => DashboardApi.createPlaceholderRooms());
  let setRooms = match[1];
  let match$1 = React.useState(() => 0);
  let setTick = match$1[1];
  let match$2 = React.useState(() => true);
  let setIsLoading = match$2[1];
  let match$3 = React.useState(() => {});
  let setErrorMessage = match$3[1];
  let errorMessage = match$3[0];
  let match$4 = React.useState(() => {});
  let setPendingRoomId = match$4[1];
  let pendingRoomId = match$4[0];
  let loadDashboard = () => {
    Stdlib_Promise.$$catch(DashboardApi.fetchDashboardRooms(apiBaseUrl).then(nextRooms => {
      setRooms(_previous => nextRooms);
      setErrorMessage(_previous => {});
      setIsLoading(_previous => false);
      return Promise.resolve();
    }), _error => {
      setErrorMessage(_previous => "Impossible de contacter dashboard-api.");
      setIsLoading(_previous => false);
      return Promise.resolve();
    });
  };
  React.useEffect(() => {
    loadDashboard();
    let intervalId = setInterval(() => {
      setTick(previous => previous + 1 | 0);
      loadDashboard();
    }, 30000);
    return () => {
      clearInterval(intervalId);
    };
  }, undefined);
  let roomCards = match[0].map(room => {
    let roomId = room.id;
    let status = room.status;
    let statusTone = DashboardApi.statusTone(status);
    let tsCreate = room.tsCreate;
    let displayedElapsed = (tsCreate == null) ? room.elapsedLabel : DashboardApi.formatElapsed(tsCreate);
    let isPending = pendingMatches(pendingRoomId, roomId);
    let actionLabel = isPending ? "Mise a jour..." : "Changer le mode";
    return JsxRuntime.jsxs("article", {
      children: [
        JsxRuntime.jsxs("div", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                  children: room.label,
                  className: "roomCard__label"
                }),
                JsxRuntime.jsxs("div", {
                  children: [
                    JsxRuntime.jsx("span", {
                      children: room.temperature,
                      className: "roomCard__temperature"
                    }),
                    JsxRuntime.jsx("span", {
                      children: "°C",
                      className: "roomCard__unit"
                    })
                  ],
                  className: "roomCard__temperatureLine"
                }),
                JsxRuntime.jsxs("p", {
                  children: [
                    "Mise a jour ",
                    JsxRuntime.jsx("strong", {
                      children: displayedElapsed
                    })
                  ],
                  className: "roomCard__elapsed"
                })
              ]
            }),
            JsxRuntime.jsx("div", {
              children: "°",
              "aria-hidden": true,
              className: "thermoIcon"
            })
          ],
          className: "roomCard__body"
        }),
        JsxRuntime.jsxs("button", {
          children: [
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("p", {
                  children: "Temperature cible",
                  className: "roomCard__targetLabel"
                }),
                JsxRuntime.jsxs("p", {
                  children: [
                    room.targetTemperature,
                    JsxRuntime.jsx("span", {
                      children: "°C",
                      className: "roomCard__unit roomCard__unit--small"
                    })
                  ],
                  className: "roomCard__targetValue"
                })
              ]
            }),
            JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("span", {
                  className: "statusDot statusDot--" + statusTone
                }),
                JsxRuntime.jsx("span", {
                  children: DashboardApi.statusLabel(status),
                  className: "statusText statusText--" + statusTone
                }),
                JsxRuntime.jsx("span", {
                  children: actionLabel,
                  className: "roomCard__action"
                })
              ],
              className: "roomCard__statusGroup"
            })
          ],
          className: "roomCard__footer",
          disabled: isPending,
          onClick: _event => {
            setPendingRoomId(_previous => roomId);
            Stdlib_Promise.$$catch(DashboardApi.spinRadiatorStatus(apiBaseUrl, roomId, status).then(nextStatus => {
              setRooms(previousRooms => DashboardApi.replaceRoomStatus(previousRooms, roomId, nextStatus));
              setPendingRoomId(_previous => {});
              setErrorMessage(_previous => {});
              return Promise.resolve();
            }), _error => {
              setPendingRoomId(_previous => {});
              setErrorMessage(_previous => "Impossible de contacter dashboard-api.");
              return Promise.resolve();
            });
          }
        })
      ],
      className: "roomCard"
    }, roomId);
  });
  return JsxRuntime.jsxs("main", {
    children: [
      JsxRuntime.jsxs("section", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("p", {
                children: "re-dashboard",
                className: "eyebrow"
              }),
              JsxRuntime.jsx("h1", {
                children: "Dashboard chauffage"
              }),
              JsxRuntime.jsx("p", {
                children: "Le frontend React / ReScript consomme maintenant les endpoints exposes par dashboard-api.",
                className: "lead"
              })
            ]
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("span", {
                children: match$2[0] ? "Chargement..." : "Synchro toutes les 30 s",
                className: "badge"
              }),
              JsxRuntime.jsx("span", {
                children: apiBaseUrl,
                className: "badge badgeAlt"
              })
            ],
            className: "hero__meta"
          })
        ],
        className: "hero"
      }),
      errorMessage !== undefined ? JsxRuntime.jsxs("section", {
          children: [
            JsxRuntime.jsx("strong", {
              children: "Connexion API"
            }),
            JsxRuntime.jsx("span", {
              children: errorMessage
            })
          ],
          className: "alert"
        }) : null,
      JsxRuntime.jsx("section", {
        children: roomCards,
        className: "roomGrid"
      })
    ],
    className: "dashboardPage"
  });
}

let make = App;

export {
  readErrorMessage,
  pendingMatches,
  make,
}
/* react Not a pure module */
