// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DashboardApiJs from "./dashboardApi.js";

function getApiBaseUrl(prim) {
  return DashboardApiJs.getApiBaseUrl();
}

function createPlaceholderRooms(prim) {
  return DashboardApiJs.createPlaceholderRooms();
}

function fetchDashboardRooms(prim) {
  return DashboardApiJs.fetchDashboardRooms(prim);
}

function spinRadiatorStatus(prim0, prim1, prim2) {
  return DashboardApiJs.spinRadiatorStatus(prim0, prim1, prim2);
}

function replaceRoomStatus(prim0, prim1, prim2) {
  return DashboardApiJs.replaceRoomStatus(prim0, prim1, prim2);
}

function formatElapsed(prim) {
  return DashboardApiJs.formatElapsed(prim);
}

function statusLabel(prim) {
  return DashboardApiJs.statusLabel(prim);
}

function statusTone(prim) {
  return DashboardApiJs.statusTone(prim);
}

export {
  getApiBaseUrl,
  createPlaceholderRooms,
  fetchDashboardRooms,
  spinRadiatorStatus,
  replaceRoomStatus,
  formatElapsed,
  statusLabel,
  statusTone,
}
/* ./dashboardApi.js Not a pure module */
