// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

let rootElement = document.getElementById("root");

Client.createRoot(rootElement).render(JsxRuntime.jsx(App.make, {}));

export {
  rootElement,
}
/* rootElement Not a pure module */
