// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TimelineHelpersJs from "./timelineHelpers.js";

function makeDefaultTimelineFilters(prim) {
  return TimelineHelpersJs.makeDefaultTimelineFilters();
}

function readTimelineFilters(prim) {
  return TimelineHelpersJs.readTimelineFilters(prim);
}

function fetchRoomTemperatureByMode(prim0, prim1, prim2, prim3) {
  return TimelineHelpersJs.fetchRoomTemperatureByMode(prim0, prim1, prim2, prim3);
}

function buildTimelineViewModel(prim) {
  return TimelineHelpersJs.buildTimelineViewModel(prim);
}

export {
  makeDefaultTimelineFilters,
  readTimelineFilters,
  fetchRoomTemperatureByMode,
  buildTimelineViewModel,
}
/* ./timelineHelpers.js Not a pure module */
