[package]
name = "ava"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rumqttc = "0.13.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
mqtt-protocol = "0.11.2"
byteorder = "1.3"
log = "0.4"
tokio = { version = "1", optional = true }
tokio-util = { version = "0.6", features = ["codec"], optional = true }
bytes = { version = "1.0", optional = true }
thiserror = "1.0"
clap = "2"
env_logger = "0.8"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "net", "time", "io-util"] }
futures = { version = "0.3" }
