[workspace]

members = [
    "mqtt5-r",
    "move-light",
]

[workspace.dependencies]


[profile.release]
opt-level = 3
debug = false
debug-assertions = false
incremental = true

[profile.dev]
incremental = true